export const STORAGE_LEVEL_CONFIG = {
  tank: {
    iconSize: 20,
    iconContainerWidth: 'w-5',
    gap: 'gap-1',
    textMargin: '-ml-0.5',
    indentation: 'pl-0',
    padding: 'pl-2.5 pr-3 py-2',
    minHeight: 'min-h-[2.5rem]',
    width: 'w-full',
    bgColor: 'bg-storage-tank-bg',
    hoverColor: 'hover:bg-storage-tank-hover',
    selectedColor: 'bg-storage-tank-selected',
    borderColor: 'border-storage-tank-border',
    selectedBorderColor: 'border-storage-selected-border',
  },
  rack: {
    iconSize: 18,
    iconContainerWidth: 'w-[18px]',
    gap: 'gap-1',
    textMargin: '-ml-0.5',
    indentation: 'pl-4',
    padding: 'pl-2.5 pr-3 py-1.5',
    minHeight: 'min-h-[2rem]',
    width: 'w-[90%]',
    bgColor: 'bg-storage-rack-bg',
    hoverColor: 'hover:bg-storage-rack-hover',
    selectedColor: 'bg-storage-rack-selected',
    borderColor: 'border-storage-rack-border',
    selectedBorderColor: 'border-storage-selected-border',
  },
  box: {
    iconSize: 16,
    iconContainerWidth: 'w-4',
    gap: 'gap-0',
    textMargin: '-ml-0.5',
    indentation: 'pl-8',
    padding: 'pl-2.5 pr-3 py-1',
    minHeight: 'min-h-[1.75rem]',
    width: 'w-[80%]',
    bgColor: 'bg-storage-box-bg',
    hoverColor: 'hover:bg-storage-box-hover',
    selectedColor: 'bg-storage-box-selected',
    borderColor: 'border-storage-box-border',
    selectedBorderColor: 'border-storage-selected-border',
  },
} as const;

export const KEYBOARD_SHORTCUTS = {
  EXPAND: ['Enter', 'Space', 'ArrowRight'],
  COLLAPSE: ['ArrowLeft'],
  NEXT: ['ArrowDown'],
  PREVIOUS: ['ArrowUp'],
  FIRST: ['Home'],
  LAST: ['End'],
} as const;
