/**
 * Modal Preview (Dev Only)
 *
 * Renders auth and admin modals in isolation with mock data so their visuals can
 * be tuned without driving the real flows. Mounted only at /__dev/modals in dev builds.
 */

import { useCallback, useEffect, useState, type ReactNode } from 'react';

import { useSearchParams } from 'react-router-dom';

import { modalStore } from '@app/stores/modalStore';
import { adminUserService } from '@domains/admin/services/AdminUserService';
import { PasswordResetModal } from '@domains/admin/ui/components/settings-modal/PasswordResetModal';
import { useShellConfig } from '@domains/authentication/hooks/useShellConfig';
import { authService } from '@domains/authentication/services/AuthService';
import { useAuthStore } from '@domains/authentication/stores/authStore';
import { AuthGatewayPanel } from '@domains/authentication/ui/components/gateway/AuthGatewayPanel';
import { AuthLoginModal } from '@domains/authentication/ui/components/gateway/AuthLoginModal';
import { AuthRegistrationSuccessModal } from '@domains/authentication/ui/components/gateway/AuthRegistrationSuccessModal';
import { AuthSessionTimeoutModal } from '@domains/authentication/ui/components/gateway/AuthSessionTimeoutModal';
import { AuthPasswordResetPage } from '@domains/authentication/ui/components/password/AuthPasswordResetPage';

// Mirrors the chrome the registration flow declares for its success state, so the
// modal renders inside AuthGatewayPanel exactly as it does in production.
function RegistrationSuccessShell({ onClose }: { onClose: () => void }) {
  useShellConfig({
    contentKey: 'registration:success',
    variant: 'console',
    width: 'narrow',
    showBranding: true,
  });
  return <AuthRegistrationSuccessModal username="jdoe_x7k2" onClose={onClose} />;
}

function RegistrationSuccessPreview({ onClose }: { onClose: () => void }) {
  return (
    <AuthGatewayPanel>
      <RegistrationSuccessShell onClose={onClose} />
    </AuthGatewayPanel>
  );
}

// The timeout modal reads its state from the modal store; prime it on mount via the
// real action so the live countdown and tone transitions behave exactly as in prod.
function SessionTimeoutPreview({
  timeRemainingMs,
  onClose,
}: {
  timeRemainingMs: number;
  onClose: () => void;
}) {
  useEffect(() => {
    modalStore.getState().showSessionTimeoutWarning({
      timeRemainingMs,
      onStayLoggedIn: onClose,
      onLogout: onClose,
    });
    return () => modalStore.getState().hideSessionTimeoutWarning();
  }, [timeRemainingMs, onClose]);

  return <AuthSessionTimeoutModal />;
}

// Stub the two network calls so the generated-link and reset success states are
// reachable offline. Originals are restored on unmount.
function PasswordResetPreview({ onClose }: { onClose: () => void }) {
  useEffect(() => {
    const originalGenerate = adminUserService.generatePasswordResetToken;
    const originalReset = adminUserService.resetUserPassword;
    adminUserService.generatePasswordResetToken = async () => ({
      resetUrl: 'https://lab.example.com/reset-password?token=devpreviewtoken0123456789',
      expiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
      message: 'Reset link generated',
    });
    adminUserService.resetUserPassword = async () => {};
    return () => {
      adminUserService.generatePasswordResetToken = originalGenerate;
      adminUserService.resetUserPassword = originalReset;
    };
  }, []);

  return (
    <PasswordResetModal
      isOpen
      userId="dev-user-1"
      username="jane.doe"
      onClose={onClose}
      onSuccess={onClose}
    />
  );
}

const MOCK_PASSWORD_REQUIREMENTS = {
  passwordMinLength: 8,
  requireStrongPasswords: true,
  passwordRequireSpecialChars: true,
};

// Token-based reset page (the link generated by the admin modal). The dev route
// already lives inside the app router, so the token is written into the real query
// string to pick the form vs. invalid-link state — nesting a second Router throws.
// Network is stubbed so submitting the form reaches the success confirmation.
function ResetPasswordPagePreview({ token }: { token?: string }) {
  const [, setSearchParams] = useSearchParams();

  useEffect(() => {
    const originalReqs = authService.getPasswordRequirements;
    const originalReset = authService.resetPasswordWithToken;
    authService.getPasswordRequirements = async () => MOCK_PASSWORD_REQUIREMENTS;
    authService.resetPasswordWithToken = async () => {};

    setSearchParams(token ? { token } : {}, { replace: true });

    return () => {
      authService.getPasswordRequirements = originalReqs;
      authService.resetPasswordWithToken = originalReset;
      setSearchParams({}, { replace: true });
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- setSearchParams is stable; token is the only input
  }, [token]);

  return <AuthPasswordResetPage />;
}

// Forced password change on next login + its confirmation. Priming the auth store
// drives the real AuthLoginModal into each state; forceChangePassword is stubbed so
// submitting the change-required form advances to the "Password Changed" view.
function ForcedLoginPreview({ mode }: { mode: 'change-required' | 'change-success' }) {
  useEffect(() => {
    const { passwordChangeRequired, passwordChangeSuccess, forceChangePassword } =
      useAuthStore.getState();
    const originalReqs = authService.getPasswordRequirements;
    authService.getPasswordRequirements = async () => MOCK_PASSWORD_REQUIREMENTS;

    useAuthStore.setState({
      passwordChangeRequired:
        mode === 'change-required'
          ? {
              requirePasswordChange: true as const,
              tempToken: 'devpreviewtemptoken0123456789',
              user: { id: 'dev-user-1', username: 'jane.doe' },
            }
          : null,
      passwordChangeSuccess: mode === 'change-success',
      forceChangePassword: async () => {
        useAuthStore.setState({ passwordChangeSuccess: true });
        return true;
      },
    });

    return () => {
      authService.getPasswordRequirements = originalReqs;
      useAuthStore.setState({ passwordChangeRequired, passwordChangeSuccess, forceChangePassword });
    };
  }, [mode]);

  return (
    <AuthGatewayPanel>
      <AuthLoginModal />
    </AuthGatewayPanel>
  );
}

interface ModalSpec {
  id: string;
  group: string;
  label: string;
  note?: string;
  render: (close: () => void) => ReactNode;
}

const SPECS: ModalSpec[] = [
  {
    id: 'registration-success',
    group: 'Auth gateway',
    label: 'Registration Success',
    note: 'Animated checkmark + username copy, inside the gateway chrome',
    render: close => <RegistrationSuccessPreview onClose={close} />,
  },
  {
    id: 'session-timeout',
    group: 'Auth gateway',
    label: 'Session Timeout — 5:00 (calm)',
    note: 'Amber phosphor digits + diamond track',
    render: close => <SessionTimeoutPreview timeRemainingMs={5 * 60 * 1000} onClose={close} />,
  },
  {
    id: 'session-timeout-warn',
    group: 'Auth gateway',
    label: 'Session Timeout — 0:45 (warn)',
    note: 'Crimson tint, bloom heartbeat',
    render: close => <SessionTimeoutPreview timeRemainingMs={45 * 1000} onClose={close} />,
  },
  {
    id: 'session-timeout-crit',
    group: 'Auth gateway',
    label: 'Session Timeout — 0:12 (critical)',
    note: 'Bright crimson, faster beat',
    render: close => <SessionTimeoutPreview timeRemainingMs={12 * 1000} onClose={close} />,
  },
  {
    id: 'password-reset',
    group: 'Admin',
    label: 'Password Reset',
    note: 'Direct-set tab + generated-link success state (network stubbed)',
    render: close => <PasswordResetPreview onClose={close} />,
  },
  {
    id: 'reset-page-form',
    group: 'Password reset (user side)',
    label: 'Set Password — token reset',
    note: 'AuthPasswordResetPage form; submitting reveals the success confirmation',
    render: () => <ResetPasswordPagePreview token="devpreviewtoken0123456789" />,
  },
  {
    id: 'reset-page-invalid',
    group: 'Password reset (user side)',
    label: 'Invalid / Expired Link',
    note: 'AuthPasswordResetPage with no token',
    render: () => <ResetPasswordPagePreview />,
  },
  {
    id: 'login-change-required',
    group: 'Password reset (user side)',
    label: 'Forced Change on Login',
    note: 'AuthLoginModal change-required; submitting advances to "Password Changed"',
    render: () => <ForcedLoginPreview mode="change-required" />,
  },
  {
    id: 'login-change-success',
    group: 'Password reset (user side)',
    label: 'Password Changed (confirmation)',
    note: 'AuthLoginModal change-success state',
    render: () => <ForcedLoginPreview mode="change-success" />,
  },
];

export function ModalPreviewPage() {
  const [activeId, setActiveId] = useState<string | null>(null);
  const close = useCallback(() => setActiveId(null), []);
  const active = SPECS.find(spec => spec.id === activeId);
  const groups = Array.from(new Set(SPECS.map(spec => spec.group)));

  // Page/login previews are full-screen and have no built-in close button.
  useEffect(() => {
    if (!activeId) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setActiveId(null);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [activeId]);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-2xl px-8 py-12">
        <header className="mb-8">
          <span className="type-label text-label-2xs tracking-label-wide text-primary">
            Dev · /__dev/modals
          </span>
          <h1 className="mt-1 text-xl font-semibold">Modal Preview</h1>
          <p className="mt-1 text-body-sm text-muted-foreground">
            Render modals in isolation with mock data. Close a modal to pick another.
          </p>
        </header>

        {groups.map(group => (
          <section key={group} className="mb-8">
            <h2 className="mb-3 type-label text-label-xs text-muted-foreground">{group}</h2>
            <div className="space-y-2">
              {SPECS.filter(spec => spec.group === group).map(spec => (
                <button
                  key={spec.id}
                  type="button"
                  onClick={() => setActiveId(spec.id)}
                  className="flex w-full flex-col items-start rounded-md border border-line-soft bg-card px-4 py-3 text-left transition-colors hover:border-primary/60"
                >
                  <span className="text-body font-medium">{spec.label}</span>
                  {spec.note && (
                    <span className="mt-0.5 text-caption text-muted-foreground">{spec.note}</span>
                  )}
                </button>
              ))}
            </div>
          </section>
        ))}
      </div>

      {active && (
        <button
          type="button"
          onClick={close}
          className="fixed right-4 top-4 z-[60] rounded-md border border-line-soft bg-card px-3 py-1.5 font-mono text-data-sm text-muted-foreground transition-colors hover:border-primary/60 hover:text-foreground"
        >
          Close preview · Esc
        </button>
      )}
      {active?.render(close)}
    </div>
  );
}
