/**
 * @odysseus/shared-schemas
 *
 * Validation schemas used by both client and server.
 */

// Tubes
export {
  CONCENTRATION_UNITS,
  UNKNOWN_RESEARCHER,
  tubeLocationSchema,
  tubeSampleSchema,
  tubeTimestampsSchema,
  tubeDataSchema,
  tubeDataArraySchema,
  createTubeRequestSchema,
  updateTubeRequestSchema,
  tubeQueryFiltersSchema,
  batchTubeOperationSchema,
  tubeValidationResultSchema,
  type TubeData,
  type TubeLocation,
  type TubeSample,
  type TubeUpdateSample,
  type TubeTimestamps,
  type CreateTubeRequest,
  type UpdateTubeRequest,
  type TubeQueryFilters,
  type BatchTubeOperation,
  type TubeValidationResult,
  type ConcentrationUnit,
  type CreateTubeFormInput,
  type UpdateTubeFormInput,
  validateTubePosition,
  parseConcentrationInput,
  concentrationPreprocessor,
  concentrationPreprocessorNullable,
  parseDate,
  datePreprocessor,
  datePreprocessorNullable,
  optionalFromEmpty,
  nullableOptionalFromEmpty,
  concentrationUnitRefinement,
  formatConcentrationDisplay,
  formatTubeLocation,
  formatTubeLocationShort,
  formatTubeDate,
  parseConcentrationDisplay,
  type TubeLocationFormatOptions,
  tubeDataToCreateRequest,
  tubeDataArrayToCreateRequests,
  lockTubesRequestSchema,
  unlockTubesRequestSchema,
  shareTubeAccessRequestSchema,
  revokeTubeAccessRequestSchema,
  skippedTubeSchema,
  batchLockResultSchema,
  batchUnlockResultSchema,
  shareAccessResultSchema,
  revokeAccessResultSchema,
  type LockTubesRequest,
  type UnlockTubesRequest,
  type ShareTubeAccessRequest,
  type RevokeTubeAccessRequest,
  type SkippedTube,
  type BatchLockResult,
  type BatchUnlockResult,
  type ShareAccessResult,
  type RevokeAccessResult,
} from './tubes';

// Lookups
export {
  LOOKUP_CATEGORIES,
  lookupValueSchema,
  lookupValueWithCountSchema,
  createLookupValueRequestSchema,
  renameLookupValueRequestSchema,
  type LookupCategory,
  type LookupValue,
  type LookupValueWithCount,
  type CreateLookupValueRequest,
  type RenameLookupValueRequest,
} from './lookups/lookupSchemas';

// Search
export {
  SearchFiltersSchema,
  AdvancedSearchOptionsSchema,
  SearchResultSchema,
  SearchResultsSchema,
  GroupedResultSchema,
  SearchSuggestionsResponseSchema,
  type SearchFilters,
  type AdvancedSearchOptions,
  type SearchResult,
  type SearchResults,
  type GroupedResult,
  type SearchSuggestionsResponse,
} from './search/searchSchemas';

// Researchers
export {
  researcherSchema,
  createResearcherProfileSchema,
  updateResearcherProfileSchema,
  researcherQueryFiltersSchema,
  adminResearcherSchema,
  type Researcher,
  type CreateResearcherProfile,
  type UpdateResearcherProfile,
  type ResearcherQueryFilters,
  type AdminResearcher,
  formatResearcherListDisplay,
  formatResearcherDropdownDisplay,
  formatResearcherFullDisplay,
  calculateNameSimilarity,
  findSimilarResearchers,
} from './researchers/researcherSchemas';

// Transport
export {
  successEnvelopeSchema,
  errorEnvelopeSchema,
  ApiError,
} from './infrastructure/transportSchemas';

// Storage
export {
  GridConfigurationSchema,
  BoxConfigurationSchema,
  RackConfigurationSchema,
  TankConfigurationSchema,
  ColorSchemeSchema,
  EquipmentConfigurationSchema,
  LabConfigurationSchema,
  GlobalSettingsSchema,
  SystemConfigurationSchema,
  ConfigurationResponseSchema,
  SaveConfigurationRequestSchema,
  type GridConfiguration,
  type BoxConfiguration,
  type RackConfiguration,
  type TankConfiguration,
  type ColorScheme,
  type EquipmentConfiguration,
  type LabConfiguration,
  type GlobalSettings,
  type SystemConfiguration,
  type ConfigurationResponse,
  type SaveConfigurationRequest,
  formatResourceDisplayName,
  positionDisplayFormatSchema,
  alphanumericConfigSchema,
  positionDisplayConfigSchema,
  positionDisplayPreferenceSchema,
  POSITION_DISPLAY_PRESETS,
  type PositionDisplayFormat,
  type AlphanumericConfig,
  type PositionDisplayConfig,
  type PositionDisplayPreference,
  generateAlphabeticLabels,
  generateNumericLabels,
  createAlphanumericConfig,
  createNumericConfig,
  getDefaultPositionDisplay,
  positionToLabel,
  labelToPosition,
  isValidPositionLabel,
  generatePositionLabels,
} from './storage';

// API Constants
export {
  API_ERROR_CODES,
} from './api/apiSchemas';

// System Constants
export {
  EQUIPMENT_DEFAULTS,
  VALIDATION_LIMITS,
  SYSTEM_DEFAULTS,
  NAMING_PATTERNS,
  GRID_TEMPLATES,
  DEFAULT_GRID_CONFIG,
} from './constants';

// Admin
export {
  securityConfigSchema,
  updateSecurityConfigSchema,
  adminUserSchema,
  systemMetricsSchema,
  auditLogEntrySchema,
  auditLogFiltersSchema,
  userSessionSchema,
  securityConfigResponseSchema,
  adminUsersResponseSchema,
  systemMetricsResponseSchema,
  auditLogResponseSchema,
  DEFAULT_SECURITY_CONFIG,
  type SecurityConfig,
  type UpdateSecurityConfig,
  type AdminUser,
  type SystemMetrics,
  type AuditLogEntry,
  type AuditLogFilters,
  type UserSession,
  type SecurityConfigResponse,
  type AdminUsersResponse,
  type SystemMetricsResponse,
  type AuditLogResponse,
} from './admin/adminSchemas';

// Authentication
export {
  registerWithResearcherSchema,
  verifyEmailRequestSchema,
  resendVerificationRequestSchema,
  verificationStatusResponseSchema,
  systemAdminSetupSchema,
  validateInviteCodeRequestSchema,
  validateInviteCodeResponseSchema,
  type RegisterWithResearcherRequest,
  type VerifyEmailRequest,
  type ResendVerificationRequest,
  type VerificationStatusResponse,
  type SystemAdminSetupRequest,
  type ValidateInviteCodeRequest,
  type ValidateInviteCodeResponse,
  PasswordValidator,
  type PasswordRequirementsConfig,
  type PasswordRequirement,
  type PasswordValidationResult,
  adminResetPasswordRequestSchema,
  generatePasswordResetTokenResponseSchema,
  resetPasswordWithTokenRequestSchema,
  forceChangePasswordRequestSchema,
  passwordChangeRequiredResponseSchema,
  type AdminResetPasswordRequest,
  type GeneratePasswordResetTokenResponse,
  type ResetPasswordWithTokenRequest,
  type ForceChangePasswordRequest,
  type PasswordChangeRequiredResponse,
} from './auth';

// Labs
export {
  labDataSchema,
  labPublicDataSchema,
  inviteCodeDataSchema,
  createLabRequestSchema,
  createInviteCodeRequestSchema,
  labDetailsSchema,
  labDetailsUserSchema,
  type LabData,
  type LabPublicData,
  type InviteCodeData,
  type CreateLabRequest,
  type CreateInviteCodeRequest,
  type LabDetails,
  type LabDetailsUser,
  type LabDetailsResearcher,
  systemOverviewSchema,
  type SystemOverview,
} from './labs/labSchemas';

// Users
export {
  userSettingsSchema,
  updateUserSettingsRequestSchema,
  userSettingsResponseSchema,
  themePreferenceSchema,
  DEFAULT_USER_SETTINGS,
  type UserSettings,
  type UpdateUserSettingsRequest,
  type UserSettingsResponse,
  type ThemePreference,
  userLookupRequestSchema,
  userDisplayInfoSchema,
  userLookupResponseSchema,
  activeUsersListResponseSchema,
  type UserLookupRequest,
  type UserDisplayInfo,
  type UserLookupResponse,
  type ActiveUsersListResponse,
} from './users';

// Demo
export {
  demoLimitsSchema,
  updateDemoLimitsSchema,
  seedDemoResponseSchema,
  unseedDemoResponseSchema,
  DEMO_LIMITS_DEFAULTS,
  type DemoLimits,
  type UpdateDemoLimits,
  type SeedDemoResponse,
  type UnseedDemoResponse,
} from './demo/demoSchemas';

// Persons
export {
  personSchema,
  updatePersonProfileSchema,
  type Person,
  type UpdatePersonProfile,
  type NameSortable,
  sortByName,
} from './persons/personSchemas';
