/**
 * Shared Validation Schemas
 *
 * Public exports for all Zod schemas used by both client and server.
 */

// Tubes
export {
  CONCENTRATION_UNITS,
  UNKNOWN_RESEARCHER,
  tubeLocationSchema,
  tubeSampleSchema,
  tubeTimestampsSchema,
  tubeDataSchema,
  tubeDataArraySchema,
  rackTubeSchema,
  tubeLocationCountSchema,
  createTubeRequestSchema,
  updateTubeRequestSchema,
  bulkTubeOperationSchema,
  TUBE_FILTERABLE_FIELDS,
  tubeFilterOptionsResponseSchema,
  tubeValidationResultSchema,
  type TubeData,
  type TubeLocation,
  type TubeSample,
  type RackTube,
  type TubeLocationCount,
  type TubeUpdateSample,
  type TubeTimestamps,
  type CreateTubeRequest,
  type UpdateTubeRequest,
  type BulkTubeOperation,
  type TubeFilterableField,
  type TubeFilterOptions,
  type TubeValidationResult,
  type ConcentrationUnit,
  type CreateTubeFormInput,
  type UpdateTubeFormInput,
  validateTubePosition,
  parseConcentrationInput,
  concentrationPreprocessor,
  concentrationPreprocessorNullable,
  parseDate,
  datePreprocessor,
  datePreprocessorNullable,
  optionalFromEmpty,
  nullableOptionalFromEmpty,
  concentrationUnitRefinement,
  formatConcentrationDisplay,
  formatTubeLocation,
  formatTubeLocationShort,
  formatTubeDate,
  parseConcentrationDisplay,
  type TubeLocationFormatOptions,
  tubeDataToCreateRequest,
  lockTubesRequestSchema,
  unlockTubesRequestSchema,
  shareTubeAccessRequestSchema,
  revokeTubeAccessRequestSchema,
  skippedTubeSchema,
  bulkLockResultSchema,
  bulkUnlockResultSchema,
  shareAccessResultSchema,
  revokeAccessResultSchema,
  type LockTubesRequest,
  type UnlockTubesRequest,
  type ShareTubeAccessRequest,
  type RevokeTubeAccessRequest,
  type SkippedTube,
  type BulkLockResult,
  type BulkUnlockResult,
  type ShareAccessResult,
  type RevokeAccessResult,
  bulkDeleteResponseSchema,
  pasteTubesResponseSchema,
  bulkUpdateResponseSchema,
  bulkFetchResponseSchema,
  bulkMoveRequestSchema,
  bulkMoveResponseSchema,
  type BulkDeleteResponse,
  type PasteTubesResponse,
  type BulkUpdateResponse,
  type BulkMoveRequest,
  type BulkMoveResponse,
} from './tubes';

// Lookups
export {
  LOOKUP_CATEGORIES,
  lookupValueSchema,
  lookupValueWithCountSchema,
  createLookupValueRequestSchema,
  renameLookupValueRequestSchema,
  type LookupCategory,
  type LookupValue,
  type LookupValueWithCount,
  type CreateLookupValueRequest,
  type RenameLookupValueRequest,
} from './lookups/lookupSchemas';

// Search
export {
  SearchFiltersSchema,
  AdvancedSearchOptionsSchema,
  SearchResultSchema,
  SearchResultsSchema,
  GroupedResultSchema,
  SearchSuggestionsResponseSchema,
  type SearchFilters,
  type AdvancedSearchOptions,
  type SearchResult,
  type SearchResults,
  type GroupedResult,
  type SearchSuggestionsResponse,
} from './search/searchSchemas';

// Researchers
export {
  researcherSchema,
  createResearcherProfileSchema,
  updateResearcherProfileSchema,
  adminResearcherSchema,
  type Researcher,
  type CreateResearcherProfile,
  type UpdateResearcherProfile,
  type AdminResearcher,
  formatResearcherListDisplay,
  formatResearcherDropdownDisplay,
  formatResearcherFullDisplay,
  calculateNameSimilarity,
  findSimilarResearchers,
} from './researchers/researcherSchemas';

// Transport
export {
  successEnvelopeSchema,
  errorEnvelopeSchema,
  messageResponseSchema,
  emptyResponseSchema,
  versionInfoSchema,
  ApiError,
  type MessageResponse,
  type EmptyResponse,
  type VersionInfo,
} from './infrastructure/transportSchemas';

// Storage
export {
  GridConfigurationSchema,
  BoxConfigurationSchema,
  RackConfigurationSchema,
  TankConfigurationSchema,
  ColorSchemeSchema,
  EquipmentConfigurationSchema,
  LabConfigurationSchema,
  GlobalSettingsSchema,
  SystemConfigurationSchema,
  StorageResponseSchema,
  SaveStorageRequestSchema,
  type GridConfiguration,
  type BoxConfiguration,
  type RackConfiguration,
  type TankConfiguration,
  type ColorScheme,
  type EquipmentConfiguration,
  type LabConfiguration,
  type GlobalSettings,
  type SystemConfiguration,
  type StorageResponse,
  type SaveStorageRequest,
  formatStorageDisplayName,
  positionDisplayFormatSchema,
  alphanumericConfigSchema,
  positionDisplayConfigSchema,
  positionDisplayPreferenceSchema,
  POSITION_DISPLAY_PRESETS,
  type PositionDisplayFormat,
  type AlphanumericConfig,
  type PositionDisplayConfig,
  type PositionDisplayPreference,
  generateAlphabeticLabels,
  generateNumericLabels,
  createAlphanumericConfig,
  createNumericConfig,
  getDefaultPositionDisplay,
  positionToLabel,
  labelToPosition,
  isValidPositionLabel,
  generatePositionLabels,
  addTankResponseSchema,
  addRacksResponseSchema,
  addBoxesResponseSchema,
  bulkOperationResponseSchema,
  positionDisplayPresetsResponseSchema,
  type AddTankResponse,
  type AddRacksResponse,
  type AddBoxesResponse,
  type BulkOperationResponse,
  type PositionDisplayPresetsResponse,
} from './storage';

// API Constants
export {
  API_ERROR_CODES,
} from './api/apiSchemas';

// System Constants
export {
  EQUIPMENT_DEFAULTS,
  VALIDATION_LIMITS,
  SYSTEM_DEFAULTS,
  NAMING_PATTERNS,
  GRID_TEMPLATES,
  DEFAULT_GRID_CONFIG,
} from './constants';

// Admin
export {
  securityConfigSchema,
  updateSecurityConfigSchema,
  DEFAULT_SECURITY_CONFIG,
  adminUserSchema,
  systemMetricsSchema,
  securityConfigDataSchema,
  adminUsersListSchema,
  type SecurityConfig,
  type UpdateSecurityConfig,
  type AdminUser,
  type SystemMetrics,
  type SecurityConfigData,
  type AdminUsersList,
  adminResearchersListSchema,
  inviteCodesListSchema,
  inviteCodeDataResponseSchema,
  type AdminResearchersList,
  type InviteCodesList,
  type InviteCodeDataResponse,
  auditLogEntrySchema,
  auditLogFiltersSchema,
  auditStatisticsSchema,
  retentionMetricsSchema,
  retentionPolicySchema,
  auditArchiveResponseSchema,
  paginationSchema,
  auditSearchResponseSchema,
  auditLogDataSchema,
  type AuditLogEntry,
  type AuditLogFilters,
  type AuditStatistics,
  type RetentionMetrics,
  type RetentionPolicy,
  type AuditArchiveResponse,
  type Pagination,
  type AuditSearchResponse,
  type AuditLogData,
  entityHistoryResponseSchema,
  auditStatisticsDataSchema,
  retentionMetricsDataSchema,
  retentionPolicyDataSchema,
  type EntityHistoryResponse,
  type AuditStatisticsData,
  type RetentionMetricsData,
  type RetentionPolicyData,
  sessionOverviewSchema,
  tokenHealthSchema,
  securityOverviewResponseSchema,
  activeSessionEntrySchema,
  activeSessionsResponseSchema,
  ipActivityEntrySchema,
  ipActivityResponseSchema,
  purgeExpiredResponseSchema,
  type SessionOverview,
  type TokenHealth,
  type SecurityOverviewResponse,
  type ActiveSessionEntry,
  type ActiveSessionsResponse,
  type IpActivityEntry,
  type IpActivityResponse,
  type PurgeExpiredResponse,
  bulkRevokeSessionsRequestSchema,
  bulkRevokeResponseSchema,
  type BulkRevokeSessionsRequest,
  type BulkRevokeResponse,
  failedLoginEntrySchema,
  failedLoginsResponseSchema,
  type FailedLoginEntry,
  type FailedLoginsResponse,
  sessionActivityEntrySchema,
  sessionActivityResponseSchema,
  type SessionActivityEntry,
  type SessionActivityResponse,
  boxUtilizationSchema,
  rackUtilizationSchema,
  tankUtilizationSchema,
  nearCapacityBoxSchema,
  labStorageAnalyticsResponseSchema,
  labStorageSummarySchema,
  crossLabStorageAnalyticsResponseSchema,
  type BoxUtilization,
  type RackUtilization,
  type TankUtilization,
  type NearCapacityBox,
  type LabStorageAnalyticsResponse,
  type LabStorageSummary,
  type CrossLabStorageAnalyticsResponse,
} from './admin';

// Authentication
export {
  registerWithProfileSchema,
  verifyEmailRequestSchema,
  resendVerificationRequestSchema,
  verificationStatusResponseSchema,
  systemAdminSetupSchema,
  validateInviteCodeRequestSchema,
  validateInviteCodeResponseSchema,
  type RegisterWithProfileRequest,
  type VerifyEmailRequest,
  type ResendVerificationRequest,
  type VerificationStatusResponse,
  type SystemAdminSetupRequest,
  type ValidateInviteCodeRequest,
  type ValidateInviteCodeResponse,
  PasswordValidator,
  type PasswordRequirementsConfig,
  type PasswordRequirement,
  type PasswordValidationResult,
  adminResetPasswordRequestSchema,
  generatePasswordResetTokenResponseSchema,
  resetPasswordWithTokenRequestSchema,
  forceChangePasswordRequestSchema,
  passwordChangeRequiredResponseSchema,
  type AdminResetPasswordRequest,
  type GeneratePasswordResetTokenResponse,
  type ResetPasswordWithTokenRequest,
  type ForceChangePasswordRequest,
  type PasswordChangeRequiredResponse,
  USER_ROLES,
  USER_STATUSES,
  type UserRole,
  type UserStatus,
  isAdminRole,
  tokenPairSchema,
  publicUserDataSchema,
  authResponseSchema,
  loginResponseSchema,
  registerWithProfileResponseSchema,
  passwordRequirementsResponseSchema,
  type TokenPair,
  type PublicUserData,
  type AuthResponse,
  type LoginResponse,
  type RegisterWithProfileResponse,
  type PasswordRequirementsResponse,
  firstTimeResponseSchema,
  verifyEmailResponseSchema,
  type FirstTimeResponse,
  type VerifyEmailResponse,
  sessionInfoResponseSchema,
  type SessionInfoResponse,
} from './auth';

// Labs
export {
  labDataSchema,
  labPublicDataSchema,
  inviteCodeDataSchema,
  createLabRequestSchema,
  createInviteCodeRequestSchema,
  labDetailsSchema,
  labDetailsUserSchema,
  type LabData,
  type LabPublicData,
  type InviteCodeData,
  type CreateLabRequest,
  type CreateInviteCodeRequest,
  type LabDetails,
  type LabDetailsUser,
  type LabDetailsResearcher,
  systemOverviewSchema,
  type SystemOverview,
  labsListSchema,
  labDataResponseSchema,
  demoLimitsDataSchema,
  type LabsList,
  type LabDataResponse,
  type DemoLimitsData,
} from './labs/labSchemas';

// Users
export {
  userSettingsSchema,
  updateUserSettingsRequestSchema,
  userSettingsDataSchema,
  themePreferenceSchema,
  DEFAULT_USER_SETTINGS,
  type UserSettings,
  type UpdateUserSettingsRequest,
  type UserSettingsData,
  type ThemePreference,
  type ResolvedTheme,
  userLookupRequestSchema,
  userDisplayInfoSchema,
  usersLookupListSchema,
  type UserLookupRequest,
  type UserDisplayInfo,
  type UsersLookupList,
  userSessionSchema,
  activeSessionSchema,
  revokeAllResponseSchema,
  type UserSession,
  type ActiveSession,
  type RevokeAllResponse,
} from './users';

// Demo
export {
  demoLimitsSchema,
  updateDemoLimitsSchema,
  seedDemoResponseSchema,
  unseedDemoResponseSchema,
  DEMO_LIMITS_DEFAULTS,
  type DemoLimits,
  type UpdateDemoLimits,
  type SeedDemoResponse,
  type UnseedDemoResponse,
} from './demo/demoSchemas';

// Events
export {
  tubeEventSchemas,
  researcherEventSchemas,
  configurationEventSchemas,
  userEventSchemas,
  presenceEventSchemas,
  systemAdminEventSchemas,
} from './events';

// Donors
export {
  donorSchema,
  donorWithTubeCountSchema,
  donorCollectionHistorySchema,
  createDonorRequestSchema,
  updateDonorRequestSchema,
  createCollectionHistoryRequestSchema,
  updateCollectionHistoryRequestSchema,
  donorsResponseSchema,
  donorResponseSchema,
  donorCollectionHistoryResponseSchema,
  donorCollectionHistoryEntryResponseSchema,
  donorSearchResultSchema,
  donorSearchResponseSchema,
  type Donor,
  type DonorWithTubeCount,
  type DonorCollectionHistory,
  type CreateDonorRequest,
  type UpdateDonorRequest,
  type CreateCollectionHistoryRequest,
  type UpdateCollectionHistoryRequest,
  type DonorSearchResult,
} from './donors';

// Equipment
export {
  equipmentStatusValues,
  equipmentStatusSchema,
  equipmentCategorySchema,
  createEquipmentCategoryRequestSchema,
  updateEquipmentCategoryRequestSchema,
  equipmentCategoryResponseSchema,
  equipmentCategoryListResponseSchema,
  equipmentItemSchema,
  createEquipmentItemRequestSchema,
  updateEquipmentItemRequestSchema,
  decommissionEquipmentItemRequestSchema,
  equipmentItemResponseSchema,
  equipmentItemListResponseSchema,
  equipmentItemDetailResponseSchema,
  equipmentDocumentSchema,
  createEquipmentDocumentRequestSchema,
  updateEquipmentDocumentRequestSchema,
  equipmentDocumentResponseSchema,
  equipmentMaintenanceLogSchema,
  createEquipmentMaintenanceLogRequestSchema,
  updateEquipmentMaintenanceLogRequestSchema,
  equipmentMaintenanceLogEntryResponseSchema,
  equipmentBulkMaintenanceRequestSchema,
  equipmentBulkStatusValues,
  equipmentBulkStatusSchema,
  equipmentBulkStatusRequestSchema,
  equipmentBulkRelocateRequestSchema,
  equipmentBulkResponseSchema,
  type EquipmentStatus,
  type EquipmentBulkStatus,
  type EquipmentCategory,
  type EquipmentItem,
  type EquipmentDocument,
  type EquipmentMaintenanceLog,
  type EquipmentItemDetail,
  type CreateEquipmentCategoryRequest,
  type UpdateEquipmentCategoryRequest,
  type CreateEquipmentItemRequest,
  type UpdateEquipmentItemRequest,
  type DecommissionEquipmentItemRequest,
  type CreateEquipmentDocumentRequest,
  type UpdateEquipmentDocumentRequest,
  type CreateEquipmentMaintenanceLogRequest,
  type UpdateEquipmentMaintenanceLogRequest,
  type EquipmentBulkMaintenanceRequest,
  type EquipmentBulkStatusRequest,
  type EquipmentBulkRelocateRequest,
  type EquipmentBulkResponse,
} from './equipment';

// Supplies
export {
  supplyItemStatusValues,
  supplyItemStatusSchema,
  supplyTransactionTypeValues,
  supplyTransactionTypeSchema,
  supplyBarcodeTypeValues,
  supplyBarcodeTypeSchema,
  supplyCategorySchema,
  createSupplyCategoryRequestSchema,
  updateSupplyCategoryRequestSchema,
  supplyCategoryResponseSchema,
  supplyCategoryListResponseSchema,
  supplyLocationSchema,
  createSupplyLocationRequestSchema,
  updateSupplyLocationRequestSchema,
  supplyLocationResponseSchema,
  supplyLocationListResponseSchema,
  supplyItemSchema,
  supplyItemWithStockSchema,
  createSupplyItemRequestSchema,
  updateSupplyItemRequestSchema,
  supplyItemResponseSchema,
  supplyItemListResponseSchema,
  supplyStockSchema,
  supplyBarcodeSchema,
  createSupplyBarcodeRequestSchema,
  updateSupplyBarcodeRequestSchema,
  supplyBarcodeResponseSchema,
  supplyTransactionSchema,
  recordSupplyTransactionRequestSchema,
  recordSupplyStockCountRequestSchema,
  voidSupplyTransactionRequestSchema,
  supplyBulkVoidRequestSchema,
  supplyTransactionResponseSchema,
  supplyVoidTransactionResponseSchema,
  supplyTransactionListResponseSchema,
  supplyDocumentSchema,
  createSupplyDocumentRequestSchema,
  updateSupplyDocumentRequestSchema,
  supplyDocumentResponseSchema,
  supplyDocumentListResponseSchema,
  supplyItemDetailResponseSchema,
  supplyBulkReceiveRequestSchema,
  supplyBulkIssueRequestSchema,
  supplyBulkReassignCategoryRequestSchema,
  supplyBulkArchiveRequestSchema,
  supplyBulkResponseSchema,
  supplyBulkBarcodesRequestSchema,
  supplyBulkBarcodesResponseSchema,
  supplyReorderListResponseSchema,
  supplyPackagingLevelSchema,
  createSupplyPackagingLevelRequestSchema,
  updateSupplyPackagingLevelRequestSchema,
  supplyPackagingLevelResponseSchema,
  type SupplyItemStatus,
  type SupplyTransactionType,
  type SupplyBarcodeType,
  type SupplyCategory,
  type SupplyItem,
  type SupplyItemWithStock,
  type SupplyLocation,
  type SupplyStock,
  type SupplyBarcode,
  type SupplyTransaction,
  type SupplyDocument,
  type SupplyItemDetail,
  type CreateSupplyCategoryRequest,
  type UpdateSupplyCategoryRequest,
  type CreateSupplyLocationRequest,
  type UpdateSupplyLocationRequest,
  type CreateSupplyItemRequest,
  type UpdateSupplyItemRequest,
  type CreateSupplyBarcodeRequest,
  type UpdateSupplyBarcodeRequest,
  type RecordSupplyTransactionRequest,
  type RecordSupplyStockCountRequest,
  type VoidSupplyTransactionRequest,
  type SupplyBulkVoidRequest,
  type CreateSupplyDocumentRequest,
  type UpdateSupplyDocumentRequest,
  type SupplyBulkReceiveRequest,
  type SupplyBulkIssueRequest,
  type SupplyBulkReassignCategoryRequest,
  type SupplyBulkArchiveRequest,
  type SupplyBulkResponse,
  type SupplyBulkBarcodesRequest,
  type SupplyBulkBarcodesResponse,
  type SupplyPackagingLevel,
  type CreateSupplyPackagingLevelRequest,
  type UpdateSupplyPackagingLevelRequest,
} from './supplies';

// Persons
export {
  personSchema,
  updatePersonProfileSchema,
  type Person,
  type UpdatePersonProfile,
  type NameSortable,
  sortByName,
} from './persons/personSchemas';

export { getPersonInitials, getPersonDisplayName } from './persons/personFormatters';

// Date field helpers
export {
  dateField,
  optionalDateField,
  nullableDateField,
  nullableOptionalDateField,
} from './utils/dateFields';
