/**
 * Shared Validation Schemas
 *
 * Public exports for all Zod schemas used by both client and server.
 */

// Lets client code type schemas without importing zod directly (only HttpClient may).
export type { ZodType } from 'zod';

// Tubes
export {
  CONCENTRATION_UNITS,
  tubeLocationSchema,
  tubeDataSchema,
  rackTubeSchema,
  tubeLocationCountSchema,
  createTubeRequestSchema,
  updateTubeRequestSchema,
  TUBE_FILTERABLE_FIELDS,
  TUBE_SORT_FIELDS,
  tubeFilterOptionsResponseSchema,
  type TubeData,
  type TubeSample,
  type TubeLocation,
  type RackTube,
  type TubeLocationCount,
  type CreateTubeRequest,
  type UpdateTubeRequest,
  type TubeFilterableField,
  type TubeFilterOptions,
  type ConcentrationUnit,
  type CreateTubeFormInput,
  type UpdateTubeFormInput,
  formatConcentrationDisplay,
  tubeDataToCreateRequest,
  lockTubesRequestSchema,
  unlockTubesRequestSchema,
  shareTubeAccessRequestSchema,
  revokeTubeAccessRequestSchema,
  bulkLockResultSchema,
  bulkUnlockResultSchema,
  shareAccessResultSchema,
  revokeAccessResultSchema,
  type LockTubesRequest,
  type UnlockTubesRequest,
  type ShareTubeAccessRequest,
  type RevokeTubeAccessRequest,
  type SkippedTube,
  type BulkLockResult,
  type BulkUnlockResult,
  type ShareAccessResult,
  type RevokeAccessResult,
  bulkDeleteResponseSchema,
  pasteTubesResponseSchema,
  bulkUpdateResponseSchema,
  bulkFetchResponseSchema,
  bulkMoveRequestSchema,
  bulkMoveResponseSchema,
  type BulkDeleteResponse,
  type PasteTubesResponse,
  type BulkUpdateResponse,
  type BulkMoveRequest,
  type BulkMoveResponse,
} from './tubes';

// Units
export {
  CELL_CONCENTRATION_UNITS,
  UNIT_KINDS,
  UNIT_REGISTRY,
  formatQuantity,
  formatScientific,
  pluralizeUnit,
  unitKindSchema,
  customUnitSchema,
  customUnitWithUsageSchema,
  createCustomUnitRequestSchema,
  updateCustomUnitRequestSchema,
  customUnitResponseSchema,
  customUnitListResponseSchema,
  type UnitKind,
  type UnitRegistryEntry,
  type UnitKindValue,
  type CustomUnit,
  type CustomUnitWithUsage,
  type CreateCustomUnitRequest,
  type UpdateCustomUnitRequest,
} from './units';

// Attributes
export {
  attributeValueTypeSchema,
  attributeCatalogSchema,
  attributeDefinitionSchema,
  attributeDefinitionWithUsageSchema,
  createAttributeDefinitionRequestSchema,
  updateAttributeDefinitionRequestSchema,
  attributeOptionSchema,
  attributeOptionWithUsageSchema,
  createAttributeOptionRequestSchema,
  updateAttributeOptionRequestSchema,
  attributeDefinitionResponseSchema,
  attributeDefinitionListResponseSchema,
  attributeOptionResponseSchema,
  type AttributeValueType,
  type AttributeCatalog,
  type AttributeDefinition,
  type AttributeDefinitionWithUsage,
  type AttributeOption,
  type AttributeOptionWithUsage,
  type CreateAttributeDefinitionRequest,
  type UpdateAttributeDefinitionRequest,
  type CreateAttributeOptionRequest,
  type UpdateAttributeOptionRequest,
} from './attributes';

// Locations
export {
  LOCATION_MAX_DEPTH,
  locationSchema,
  createLocationRequestSchema,
  updateLocationRequestSchema,
  locationResponseSchema,
  locationListResponseSchema,
  type Location,
  type CreateLocationRequest,
  type UpdateLocationRequest,
} from './locations';

// Documents
export { DOCUMENT_TYPE_VALUES, documentTypeSchema, type DocumentType } from './documents';

// Barcodes
export {
  BARCODE_TYPE_VALUES,
  barcodeTypeSchema,
  barcodeResolveResponseSchema,
  type BarcodeType,
  type BarcodeMatch,
} from './barcodes';

// Lookups
export {
  LOOKUP_CATEGORIES,
  lookupValueSchema,
  lookupValueWithCountSchema,
  createLookupValueRequestSchema,
  renameLookupValueRequestSchema,
  type LookupCategory,
  type LookupValue,
  type LookupValueWithCount,
} from './lookups/lookupSchemas';

// Search
export {
  AdvancedSearchOptionsSchema,
  SearchResultSchema,
  type SearchFilters,
  type AdvancedSearchOptions,
  type SearchResult,
  type GroupedResult,
} from './search/searchSchemas';

// Researchers
export {
  researcherSchema,
  createResearcherProfileSchema,
  adminResearcherSchema,
  type Researcher,
  type CreateResearcherProfile,
  type AdminResearcher,
} from './researchers/researcherSchemas';

export {
  formatResearcherListDisplay,
  formatResearcherDropdownDisplay,
} from './researchers/researcherFormatters';

// Transport
export {
  successEnvelopeSchema,
  errorEnvelopeSchema,
  messageResponseSchema,
  emptyResponseSchema,
  versionInfoSchema,
  ApiError,
  type MessageResponse,
  type VersionInfo,
} from './infrastructure/transportSchemas';

// Storage
export {
  GridConfigurationSchema,
  BoxConfigurationSchema,
  RackConfigurationSchema,
  TankConfigurationSchema,
  EquipmentConfigurationSchema,
  LabConfigurationSchema,
  SystemConfigurationSchema,
  StorageResponseSchema,
  storageVersionResponseSchema,
  type GridConfiguration,
  type BoxConfiguration,
  type RackConfiguration,
  type TankConfiguration,
  type EquipmentConfiguration,
  type LabConfiguration,
  type SystemConfiguration,
  type StorageResponse,
  formatStorageDisplayName,
  positionDisplayConfigSchema,
  positionDisplayPreferenceSchema,
  type PositionDisplayConfig,
  type PositionDisplayPreference,
  createAlphanumericConfig,
  createNumericConfig,
  getDefaultPositionDisplay,
  positionToLabel,
  labelToPosition,
  addTankResponseSchema,
  addRacksResponseSchema,
  addBoxesResponseSchema,
  bulkOperationResponseSchema,
  addTankRequestSchema,
  updateTankRequestSchema,
  addRacksRequestSchema,
  updateRackRequestSchema,
  assignRackRequestSchema,
  addBoxesRequestSchema,
  updateBoxRequestSchema,
  assignBoxRequestSchema,
  updateResourceLabelRequestSchema,
  updateSystemStorageRequestSchema,
  initializeStorageRequestSchema,
  bulkUnassignRequestSchema,
  bulkReassignRequestSchema,
} from './storage';

// API Constants
export { API_ERROR_CODES } from './api/apiSchemas';

// System Constants
export {
  EQUIPMENT_DEFAULTS,
  VALIDATION_LIMITS,
  SYSTEM_DEFAULTS,
  NAMING_PATTERNS,
  GRID_TEMPLATES,
  DEFAULT_GRID_CONFIG,
} from './constants';

// Admin
export {
  securityConfigSchema,
  updateSecurityConfigSchema,
  DEFAULT_SECURITY_CONFIG,
  adminUserSchema,
  systemMetricsSchema,
  securityConfigDataSchema,
  adminUsersListSchema,
  type SecurityConfig,
  type UpdateSecurityConfig,
  type AdminUser,
  type SystemMetrics,
  adminResearchersListSchema,
  inviteCodesListSchema,
  inviteCodeDataResponseSchema,
  type AdminResearchersList,
  auditLogEntrySchema,
  auditLogFiltersSchema,
  auditSearchQuerySchema,
  retentionMetricsSchema,
  retentionPolicySchema,
  auditArchiveResponseSchema,
  paginationSchema,
  auditSearchResponseSchema,
  type AuditLogEntry,
  type AuditLogFilters,
  type AuditSearchQuery,
  type RetentionMetrics,
  type RetentionPolicy,
  type AuditArchiveResponse,
  type Pagination,
  type AuditSearchResponse,
  retentionMetricsDataSchema,
  retentionPolicyDataSchema,
  securityOverviewResponseSchema,
  activeSessionEntrySchema,
  activeSessionsResponseSchema,
  ipActivityEntrySchema,
  ipActivityResponseSchema,
  purgeExpiredResponseSchema,
  type SecurityOverviewResponse,
  type ActiveSessionEntry,
  type ActiveSessionsResponse,
  type IpActivityEntry,
  type IpActivityResponse,
  type PurgeExpiredResponse,
  bulkRevokeSessionsRequestSchema,
  bulkRevokeResponseSchema,
  securityMonitoringQuerySchema,
  type BulkRevokeResponse,
  type SecurityMonitoringQuery,
  failedLoginEntrySchema,
  failedLoginsResponseSchema,
  type FailedLoginEntry,
  type FailedLoginsResponse,
  sessionActivityResponseSchema,
  type SessionActivityResponse,
  boxUtilizationSchema,
  rackUtilizationSchema,
  tankUtilizationSchema,
  labStorageAnalyticsResponseSchema,
  labStorageSummarySchema,
  crossLabStorageAnalyticsResponseSchema,
  type BoxUtilization,
  type RackUtilization,
  type TankUtilization,
  type LabStorageAnalyticsResponse,
  type LabStorageSummary,
  type CrossLabStorageAnalyticsResponse,
} from './admin';

// Authentication
export {
  registerWithProfileSchema,
  validateInviteCodeRequestSchema,
  validateInviteCodeResponseSchema,
  type RegisterWithProfileRequest,
  type ValidateInviteCodeResponse,
  PasswordValidator,
  type PasswordRequirementsConfig,
  type PasswordRequirement,
  type PasswordValidationResult,
  adminResetPasswordRequestSchema,
  generatePasswordResetTokenResponseSchema,
  resetPasswordWithTokenRequestSchema,
  forceChangePasswordRequestSchema,
  changePasswordRequestSchema,
  passwordChangeRequiredResponseSchema,
  type GeneratePasswordResetTokenResponse,
  type PasswordChangeRequiredResponse,
  USER_ROLES,
  USER_STATUSES,
  type UserRole,
  type UserStatus,
  isAdminRole,
  tokenPairSchema,
  publicUserDataSchema,
  authResponseSchema,
  refreshTokenResponseSchema,
  loginResponseSchema,
  registerWithProfileResponseSchema,
  passwordRequirementsResponseSchema,
  type TokenPair,
  type PublicUserData,
  type AuthResponse,
  type RefreshTokenResponse,
  type LoginResponse,
  type RegisterWithProfileResponse,
  type PasswordRequirementsResponse,
  firstTimeResponseSchema,
  verifyEmailResponseSchema,
  sessionInfoResponseSchema,
  type FirstTimeResponse,
  type VerifyEmailResponse,
  type SessionInfoResponse,
} from './auth';

// Labs
export {
  labDataSchema,
  inviteCodeDataSchema,
  createLabRequestSchema,
  createInviteCodeRequestSchema,
  labDetailsSchema,
  labDetailsUserSchema,
  type LabData,
  type InviteCodeData,
  type CreateInviteCodeRequest,
  type LabDetails,
  type LabDetailsUser,
  type LabDetailsResearcher,
  systemOverviewSchema,
  type SystemOverview,
  labsListSchema,
  labDataResponseSchema,
  demoLimitsDataSchema,
  type DemoLimitsData,
} from './labs/labSchemas';

// Users
export {
  userSettingsSchema,
  userSettingsDataSchema,
  themePreferenceSchema,
  DEFAULT_USER_SETTINGS,
  type UserSettings,
  type ThemePreference,
  type ResolvedTheme,
  userLookupRequestSchema,
  userDisplayInfoSchema,
  usersLookupListSchema,
  type UserDisplayInfo,
  activeSessionSchema,
  type ActiveSession,
} from './users';

// Demo
export {
  demoLimitsSchema,
  updateDemoLimitsSchema,
  seedDemoResponseSchema,
  unseedDemoResponseSchema,
  DEMO_LIMITS_DEFAULTS,
  type DemoLimits,
  type SeedDemoResponse,
  type UnseedDemoResponse,
} from './demo/demoSchemas';

// Events
export {
  tubeEventSchemas,
  researcherEventSchemas,
  configurationEventSchemas,
  userEventSchemas,
  presenceEventSchemas,
  systemAdminEventSchemas,
} from './events';

// Donors
export {
  donorSchema,
  donorWithTubeCountSchema,
  donorCollectionHistorySchema,
  createDonorRequestSchema,
  updateDonorRequestSchema,
  createCollectionHistoryRequestSchema,
  updateCollectionHistoryRequestSchema,
  donorsResponseSchema,
  donorResponseSchema,
  donorCollectionHistoryResponseSchema,
  donorCollectionHistoryEntryResponseSchema,
  donorSearchResultSchema,
  donorSearchResponseSchema,
  type Donor,
  type DonorWithTubeCount,
  type DonorCollectionHistory,
  type CreateDonorRequest,
  type UpdateDonorRequest,
  type CreateCollectionHistoryRequest,
  type UpdateCollectionHistoryRequest,
  type DonorSearchResult,
} from './donors';

// Equipment
export {
  equipmentStatusValues,
  equipmentStatusSchema,
  equipmentCategorySchema,
  createEquipmentCategoryRequestSchema,
  updateEquipmentCategoryRequestSchema,
  equipmentCategoryResponseSchema,
  equipmentCategoryListResponseSchema,
  equipmentItemSchema,
  createEquipmentItemRequestSchema,
  updateEquipmentItemRequestSchema,
  decommissionEquipmentItemRequestSchema,
  equipmentItemResponseSchema,
  equipmentItemListResponseSchema,
  equipmentItemDetailResponseSchema,
  equipmentDocumentSchema,
  createEquipmentDocumentRequestSchema,
  updateEquipmentDocumentRequestSchema,
  equipmentDocumentResponseSchema,
  equipmentMaintenanceLogSchema,
  createEquipmentMaintenanceLogRequestSchema,
  updateEquipmentMaintenanceLogRequestSchema,
  equipmentMaintenanceLogEntryResponseSchema,
  equipmentBulkMaintenanceRequestSchema,
  equipmentBulkStatusValues,
  equipmentBulkStatusSchema,
  equipmentBulkStatusRequestSchema,
  equipmentBulkRelocateRequestSchema,
  equipmentBulkResponseSchema,
  type EquipmentStatus,
  type EquipmentCategory,
  type EquipmentItem,
  type EquipmentDocument,
  type EquipmentMaintenanceLog,
  type EquipmentItemDetail,
  type CreateEquipmentCategoryRequest,
  type UpdateEquipmentCategoryRequest,
  type CreateEquipmentItemRequest,
  type UpdateEquipmentItemRequest,
  type DecommissionEquipmentItemRequest,
  type CreateEquipmentDocumentRequest,
  type UpdateEquipmentDocumentRequest,
  type CreateEquipmentMaintenanceLogRequest,
  type UpdateEquipmentMaintenanceLogRequest,
  type EquipmentBulkStatusRequest,
  type EquipmentBulkRelocateRequest,
  type EquipmentBulkResponse,
} from './equipment';

// Supplies
export {
  supplyItemStatusValues,
  supplyItemStatusSchema,
  supplyTransactionTypeSchema,
  supplyCategorySchema,
  createSupplyCategoryRequestSchema,
  updateSupplyCategoryRequestSchema,
  supplyCategoryResponseSchema,
  supplyCategoryListResponseSchema,
  supplyItemSchema,
  supplyItemWithStockSchema,
  createSupplyItemRequestSchema,
  updateSupplyItemRequestSchema,
  supplyItemResponseSchema,
  supplyItemListResponseSchema,
  supplyStockSchema,
  supplyBarcodeSchema,
  createSupplyBarcodeRequestSchema,
  updateSupplyBarcodeRequestSchema,
  supplyBarcodeResponseSchema,
  supplyTransactionSchema,
  recordSupplyTransactionRequestSchema,
  recordSupplyStockCountRequestSchema,
  voidSupplyTransactionRequestSchema,
  supplyBulkVoidRequestSchema,
  supplyTransactionResponseSchema,
  supplyVoidTransactionResponseSchema,
  supplyTransactionListResponseSchema,
  supplyDocumentSchema,
  createSupplyDocumentRequestSchema,
  updateSupplyDocumentRequestSchema,
  supplyDocumentResponseSchema,
  supplyItemDetailResponseSchema,
  supplyBulkReceiveRequestSchema,
  supplyBulkIssueRequestSchema,
  supplyBulkReassignCategoryRequestSchema,
  supplyBulkArchiveRequestSchema,
  supplyBulkResponseSchema,
  supplyBulkBarcodesRequestSchema,
  supplyBulkBarcodesResponseSchema,
  supplyPackagingLevelSchema,
  createSupplyPackagingLevelRequestSchema,
  supplyPackagingLevelResponseSchema,
  type SupplyItemStatus,
  type SupplyTransactionType,
  type SupplyCategory,
  type SupplyItem,
  type SupplyItemWithStock,
  type SupplyBarcode,
  type SupplyTransaction,
  type SupplyVoidTransactionResponse,
  type SupplyDocument,
  type SupplyItemDetail,
  type CreateSupplyCategoryRequest,
  type UpdateSupplyCategoryRequest,
  type CreateSupplyItemRequest,
  type UpdateSupplyItemRequest,
  type CreateSupplyBarcodeRequest,
  type UpdateSupplyBarcodeRequest,
  type RecordSupplyTransactionRequest,
  type RecordSupplyStockCountRequest,
  type VoidSupplyTransactionRequest,
  type SupplyBulkVoidRequest,
  type CreateSupplyDocumentRequest,
  type UpdateSupplyDocumentRequest,
  type SupplyBulkReceiveRequest,
  type SupplyBulkIssueRequest,
  type SupplyBulkResponse,
  type SupplyBulkBarcodesResponse,
  type SupplyPackagingLevel,
  type CreateSupplyPackagingLevelRequest,
} from './supplies';

// Reagents
export {
  reagentItemStatusValues,
  reagentItemStatusSchema,
  reagentTransactionTypeSchema,
  reagentLotStatusSchema,
  reagentCategorySchema,
  createReagentCategoryRequestSchema,
  updateReagentCategoryRequestSchema,
  reagentCategoryResponseSchema,
  reagentCategoryListResponseSchema,
  reagentAttributeSummarySchema,
  reagentItemSchema,
  reagentItemWithStockSchema,
  createReagentItemRequestSchema,
  updateReagentItemRequestSchema,
  reagentItemResponseSchema,
  reagentItemListResponseSchema,
  reagentLotSchema,
  updateReagentLotRequestSchema,
  reagentLotResponseSchema,
  reagentBarcodeSchema,
  createReagentBarcodeRequestSchema,
  updateReagentBarcodeRequestSchema,
  reagentBarcodeResponseSchema,
  reagentTransactionSchema,
  recordReagentTransactionRequestSchema,
  recordReagentStockCountRequestSchema,
  voidReagentTransactionRequestSchema,
  reagentBulkVoidRequestSchema,
  reagentVoidTransactionResponseSchema,
  reagentTransactionListResponseSchema,
  reagentDocumentSchema,
  createReagentDocumentRequestSchema,
  updateReagentDocumentRequestSchema,
  reagentDocumentResponseSchema,
  reagentPackagingLevelSchema,
  createReagentPackagingLevelRequestSchema,
  reagentPackagingLevelResponseSchema,
  reagentAttributeValueSchema,
  reagentAttributeValueListResponseSchema,
  setReagentAttributeValueRequestSchema,
  reagentItemDetailResponseSchema,
  reagentBulkReceiveRequestSchema,
  reagentBulkIssueRequestSchema,
  reagentBulkReassignCategoryRequestSchema,
  reagentBulkArchiveRequestSchema,
  reagentBulkResponseSchema,
  reagentBulkBarcodesRequestSchema,
  reagentBulkBarcodesResponseSchema,
  reagentBulkLotLabelsResponseSchema,
  type ReagentItemStatus,
  type ReagentTransactionType,
  type ReagentLotStatus,
  type ReagentCategory,
  type ReagentItem,
  type ReagentItemWithStock,
  type ReagentLot,
  type ReagentBarcode,
  type ReagentTransaction,
  type ReagentVoidTransactionResponse,
  type ReagentDocument,
  type ReagentPackagingLevel,
  type ReagentAttributeValue,
  type ReagentAttributeSummary,
  type ReagentItemDetail,
  type CreateReagentCategoryRequest,
  type UpdateReagentCategoryRequest,
  type CreateReagentItemRequest,
  type UpdateReagentItemRequest,
  type UpdateReagentLotRequest,
  type CreateReagentBarcodeRequest,
  type UpdateReagentBarcodeRequest,
  type RecordReagentTransactionRequest,
  type RecordReagentStockCountRequest,
  type VoidReagentTransactionRequest,
  type ReagentBulkVoidRequest,
  type CreateReagentDocumentRequest,
  type UpdateReagentDocumentRequest,
  type CreateReagentPackagingLevelRequest,
  type SetReagentAttributeValueRequest,
  type ReagentBulkReceiveRequest,
  type ReagentBulkIssueRequest,
  type ReagentBulkResponse,
  type ReagentBulkBarcodesResponse,
  type ReagentBulkLotLabelsResponse,
} from './reagents';

// Persons
export {
  personSchema,
  updatePersonProfileSchema,
  updateMyProfileRequestSchema,
  type Person,
  type UpdatePersonProfile,
  type UpdateMyProfileRequest,
  type NameSortable,
  sortByName,
} from './persons/personSchemas';

export {
  getPersonInitials,
  getPersonDisplayName,
  getPersonSortName,
} from './persons/personFormatters';
