/**
 * Equipment Barrel
 */

export {
  equipmentStatusValues,
  equipmentStatusSchema,
  equipmentCategorySchema,
  createEquipmentCategoryRequestSchema,
  updateEquipmentCategoryRequestSchema,
  equipmentCategoryResponseSchema,
  equipmentCategoryListResponseSchema,
  equipmentItemSchema,
  createEquipmentItemRequestSchema,
  updateEquipmentItemRequestSchema,
  decommissionEquipmentItemRequestSchema,
  equipmentItemResponseSchema,
  equipmentItemListResponseSchema,
  equipmentItemDetailResponseSchema,
  equipmentAttributeValueListResponseSchema,
  setEquipmentAttributeValueRequestSchema,
  equipmentDocumentSchema,
  createEquipmentDocumentRequestSchema,
  updateEquipmentDocumentRequestSchema,
  equipmentDocumentResponseSchema,
  equipmentMaintenanceLogSchema,
  createEquipmentMaintenanceLogRequestSchema,
  updateEquipmentMaintenanceLogRequestSchema,
  equipmentMaintenanceLogEntryResponseSchema,
  equipmentBulkMaintenanceRequestSchema,
  equipmentBulkStatusValues,
  equipmentBulkStatusSchema,
  equipmentBulkStatusRequestSchema,
  equipmentBulkRelocateRequestSchema,
  equipmentBulkResponseSchema,
  type EquipmentStatus,
  type EquipmentCategory,
  type EquipmentItem,
  type EquipmentItemWithAttributes,
  type EquipmentAttributeSummary,
  type EquipmentAttributeValue,
  type SetEquipmentAttributeValueRequest,
  type EquipmentDocument,
  type EquipmentMaintenanceLog,
  type EquipmentItemDetail,
  type CreateEquipmentCategoryRequest,
  type UpdateEquipmentCategoryRequest,
  type CreateEquipmentItemRequest,
  type UpdateEquipmentItemRequest,
  type DecommissionEquipmentItemRequest,
  type CreateEquipmentDocumentRequest,
  type UpdateEquipmentDocumentRequest,
  type CreateEquipmentMaintenanceLogRequest,
  type UpdateEquipmentMaintenanceLogRequest,
  type EquipmentBulkStatusRequest,
  type EquipmentBulkRelocateRequest,
  type EquipmentBulkResponse,
} from './equipmentSchemas';
